import type {
  LocalComercial,
  Contratista,
  SolicitudConRelaciones,
  CotizacionConDetalle,
  InformeObraConDetalle,
  FormatoEspecialistaRow,
  VolumenTiendaData,
  TiempoEstadoData,
  EficienciaContratistaData,
  DesviacionPresupuestoData
} from '../types/crm.types';

export const MOCK_LOCALES: LocalComercial[] = [
  {
    id: 'loc-001',
    nombre: 'Plaza Norte - Tienda 104',
    codigo: 'LOC-PN-104',
    direccion: 'Av. Tomás Valle cruce con Panamericana Norte, Independencia',
    centro_comercial: 'Mall Plaza Norte',
    area_m2: 240.5,
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'loc-002',
    nombre: 'Jockey Plaza - Isla Gastronómica B',
    codigo: 'LOC-JP-088',
    direccion: 'Av. Javier Prado Este 4200, Santiago de Surco',
    centro_comercial: 'Jockey Plaza Shopping Center',
    area_m2: 85.0,
    created_at: '2026-01-18T09:30:00Z',
    updated_at: '2026-01-18T09:30:00Z',
  },
  {
    id: 'loc-003',
    nombre: 'Real Plaza Salaverry - Nivel 3',
    codigo: 'LOC-RPS-302',
    direccion: 'Av. General Salaverry 2370, Jesús María',
    centro_comercial: 'Real Plaza Salaverry',
    area_m2: 310.0,
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'loc-004',
    nombre: 'Mall del Sur - Tienda Ancla 2',
    codigo: 'LOC-MDS-012',
    direccion: 'Av. Los Lirios 310, San Juan de Miraflores',
    centro_comercial: 'Mall del Sur',
    area_m2: 520.0,
    created_at: '2026-02-10T11:00:00Z',
    updated_at: '2026-02-10T11:00:00Z',
  },
  {
    id: 'loc-005',
    nombre: 'Plaza San Miguel - Boulevard C',
    codigo: 'LOC-PSM-205',
    direccion: 'Av. La Marina 2000, San Miguel',
    centro_comercial: 'Plaza San Miguel',
    area_m2: 175.0,
    created_at: '2026-02-15T14:20:00Z',
    updated_at: '2026-02-15T14:20:00Z',
  },
];

export const MOCK_CONTRATISTAS: Contratista[] = [
  {
    id: 'cont-001',
    nombre_empresa: 'Obras y Adecuaciones Express S.A.C.',
    ruc_identificacion: '20554896321',
    especialidad: 'Obras Civiles, Tabiquería Drywall y Pintura',
    contacto_nombre: 'Ing. Roberto Mendoza',
    correo: 'contacto@obrasexpress.com',
    telefono: '+51 987 654 321',
    created_at: '2026-01-10T08:00:00Z',
    updated_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'cont-002',
    nombre_empresa: 'Climatización & Frío Total Perú',
    ruc_identificacion: '20601245789',
    especialidad: 'Sistemas HVAC, Chillers y Ventilación Mecánica',
    contacto_nombre: 'Ing. Patricia Arana',
    correo: 'licitaciones@friototal.pe',
    telefono: '+51 992 114 558',
    created_at: '2026-01-12T09:00:00Z',
    updated_at: '2026-01-12T09:00:00Z',
  },
  {
    id: 'cont-003',
    nombre_empresa: 'ElectroServicios e Ingeniería de Potencia',
    ruc_identificacion: '20498712365',
    especialidad: 'Tableros Eléctricos, Subestaciones y Redes TI',
    contacto_nombre: 'Ing. Fernando Gamboa',
    correo: 'proyectos@electroserv.com.pe',
    telefono: '+51 945 882 110',
    created_at: '2026-01-14T10:00:00Z',
    updated_at: '2026-01-14T10:00:00Z',
  },
];

export const MOCK_FORMATOS: FormatoEspecialistaRow[] = [
  {
    id: 'fmt-001',
    nombre: 'Lineamientos de Arquitectura y Acabados - Mall Plaza',
    descripcion: 'Normas técnicas obligatorias para frentes de tienda, piso antideslizante R11 y mamparas templadas 10mm.',
    tipo_formato: 'ARQUITECTURA_ACABADOS',
    archivo_url: 'https://storage.supabase.co/formatos_base/lineamientos_arquitectura_v2.pdf',
    contenido_estructurado: {
      piso_minimo: 'Porcelanato Alto Tráfico PEI 5',
      altura_mampara_m: 3.5,
      norma_vidrio: 'Vidrio Templado 10mm con laminado de seguridad',
    },
    embedding_vector: null,
    metadata: { version: '2.4', autor: 'Comité Técnico Mall Plaza' },
    creado_por: 'usr-ingeniero-001',
    created_at: '2026-01-05T08:00:00Z',
    updated_at: '2026-01-05T08:00:00Z',
  },
  {
    id: 'fmt-002',
    nombre: 'Guía de Instalaciones Eléctricas y Climatización',
    descripcion: 'Cálculo de cargas, tablero trifásico 380V/220V, ductería libre de halógenos y conexionado a chiller central.',
    tipo_formato: 'ELECTROMECANICA',
    archivo_url: 'https://storage.supabase.co/formatos_base/guia_electromecanica_2026.pdf',
    contenido_estructurado: {
      tipo_cable: 'Cobre libre de halógenos N2XH',
      presion_chiller_bar: 4.2,
      puesta_a_tierra_ohmios: '< 5 Ohm',
    },
    embedding_vector: null,
    metadata: { version: '3.1', autor: 'Ing. Alejandro Morales' },
    creado_por: 'usr-ingeniero-001',
    created_at: '2026-01-08T09:00:00Z',
    updated_at: '2026-01-08T09:00:00Z',
  },
  {
    id: 'fmt-003',
    nombre: 'Protocolo de Seguridad y Red Contraincendios (ACI)',
    descripcion: 'Norma NFPA 13 para rociadores automáticos upright/pendent, detectores fotoeléctricos y sensor de flujo.',
    tipo_formato: 'SISTEMA_CONTRAINCENDIOS',
    archivo_url: 'https://storage.supabase.co/formatos_base/protocolo_aci_nfpa13.pdf',
    contenido_estructurado: {
      presion_minima_psi: 65,
      espaciamiento_rociadores_m: 3.6,
      tipo_detector: 'Fotoeléctrico direccionable analógico',
    },
    embedding_vector: null,
    metadata: { version: '1.8', autor: 'Supervisión de Seguridad Obras' },
    creado_por: 'usr-ingeniero-001',
    created_at: '2026-01-12T10:00:00Z',
    updated_at: '2026-01-12T10:00:00Z',
  },
];

export const MOCK_COTIZACIONES: CotizacionConDetalle[] = [
  {
    id: 'cot-001',
    solicitud_id: 'sol-005',
    contratista_id: 'cont-001',
    archivo_url: 'https://storage.supabase.co/cotizaciones/cotizacion_obras_express_sol005.pdf',
    texto_extraido: 'Cotización técnica para adecuación integral de local comercial 240m2. Incluye demolición, drywall, porcelanato e iluminación LED...',
    categoria_detectada: 'Adecuación Integral y Acabados',
    monto_total: 48500.0,
    monto_referencia: 42000.0,
    desviacion_pct: 15.48,
    alerta_sobrecosto: true,
    confianza_ia: 94.5,
    estado_procesamiento: 'Completado',
    resultado_validacion: {
      motivo_desviacion: 'Partida de tabiquería acústica RF-60 presenta sobrecosto de +28% sobre el precio de referencia.',
      partidas_criticas: ['Tabiquería Acústica RF-60', 'Luminarias LED High-Bay 150W'],
      recomendacion_ia: 'Negociar unitario de tabiquería o solicitar desglose de mano de obra nocturna.',
      score_confianza: 94.5,
    },
    items: [
      {
        rubro: 'Obras Preliminares',
        descripcion: 'Desmontaje de drywall existente y acarreo de desmonte',
        unidad: 'GLB',
        cantidad: 1,
        precio_unitario: 3500.0,
        precio_total: 3500.0,
        precio_referencial: 3200.0,
        desviacion_pct: 9.38,
        alerta_anomalia: false,
      },
      {
        rubro: 'Tabiquería',
        descripcion: 'Tabiquería de yeso-cartón doble cara con lana de vidrio (RF-60)',
        unidad: 'M2',
        cantidad: 180,
        precio_unitario: 145.0,
        precio_total: 26100.0,
        precio_referencial: 112.0,
        desviacion_pct: 29.46,
        alerta_anomalia: true,
      },
      {
        rubro: 'Pisos',
        descripcion: 'Suministro e instalación de porcelanato 60x60 PEI 5 tráfico pesado',
        unidad: 'M2',
        cantidad: 120,
        precio_unitario: 95.0,
        precio_total: 11400.0,
        precio_referencial: 90.0,
        desviacion_pct: 5.55,
        alerta_anomalia: false,
      },
      {
        rubro: 'Electricidad',
        descripcion: 'Luminaria LED tipo panel 60x60 48W con difusor microprismático',
        unidad: 'UND',
        cantidad: 25,
        precio_unitario: 300.0,
        precio_total: 7500.0,
        precio_referencial: 240.0,
        desviacion_pct: 25.0,
        alerta_anomalia: true,
      },
    ],
    contratistas: MOCK_CONTRATISTAS[0],
    created_at: '2026-08-28T10:00:00Z',
    updated_at: '2026-08-28T10:05:00Z',
  },
];

export const MOCK_INFORMES_OBRA: InformeObraConDetalle[] = [
  {
    id: 'inf-001',
    solicitud_id: 'sol-007',
    contratista_id: 'cont-001',
    archivo_informe_url: 'https://storage.supabase.co/informes_obra/informe_final_sol007.pdf',
    galeria_fotos_urls: [
      'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541888946425-d0fbb180c5f7?w=800&auto=format&fit=crop&q=80',
    ],
    resumen_ejecutivo: 'Se completó la instalación del sistema de climatización y falso techo acústico. Pruebas de presurización ACI concluidas satisfactoriamente.',
    score_cumplimiento_ia: 88.0,
    dictamen_ingeniero: 'Pendiente',
    observaciones_ingeniero: null,
    analisis_multimodal: {
      score_general_cumplimiento: 88.0,
      hallazgos_vision: [
        {
          id: 'hall-01',
          foto_url: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&auto=format&fit=crop&q=80',
          elemento_evaluado: 'Tablero de Control Eléctrico Principal',
          estado_detectado: 'Conforme',
          confianza_score: 96.2,
          descripcion_ia: 'Se visualiza rotulado de circuitos normado, llaves termomagnéticas y cableado peinado según norma CNE.',
          especificacion_requerida: 'Rotulado indeleble y cable libre de halógenos',
        },
        {
          id: 'hall-02',
          foto_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
          elemento_evaluado: 'Rociadores de Red Contraincendios (ACI)',
          estado_detectado: 'Defecto_Leve',
          confianza_score: 84.0,
          descripcion_ia: 'Rociador ubicado a menos de 30cm del ducto de aire acondicionado, posible interferencia con patrón de descarga NFPA 13.',
          especificacion_requerida: 'Distancia mínima libre de 45cm según NFPA 13',
        },
        {
          id: 'hall-03',
          foto_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb180c5f7?w=800&auto=format&fit=crop&q=80',
          elemento_evaluado: 'Acabado de Pintura y Juntas Drywall',
          estado_detectado: 'Conforme',
          confianza_score: 91.5,
          descripcion_ia: 'Paredes con empaste uniforme, sin fisuras visibles ni burbujas en esquineros.',
          especificacion_requerida: 'Pintura Látex Lavable color blanco humo mate',
        },
      ],
      checklist_tecnico: [
        {
          id: 'chk-01',
          item: 'Protocolo de medición de pozo a tierra (< 5 Ohmios)',
          categoria: 'Electrico',
          conforme_ia: true,
          evidencia_encontrada: 'Certificado firmado por Ing. Electricista colegiado (3.8 Ohm registrados).',
          dictamen_ingeniero: 'Aprobado',
        },
        {
          id: 'chk-02',
          item: 'Prueba hidrostática de tubería ACI a 200 PSI por 2 horas',
          categoria: 'Sanitario',
          conforme_ia: true,
          evidencia_encontrada: 'Manómetro marca 200 PSI constante sin caídas de presión.',
          dictamen_ingeniero: 'Aprobado',
        },
        {
          id: 'chk-03',
          item: 'Certificado de resistencia al fuego de tabiquería RF-60',
          categoria: 'Estructural',
          conforme_ia: false,
          evidencia_encontrada: 'Falta adjuntar la ficha técnica del fabricante de la placa de yeso.',
          dictamen_ingeniero: 'Pendiente',
          observacion: 'Contratista debe enviar la ficha técnica de Placa Cortafuego.',
        },
        {
          id: 'chk-04',
          item: 'Piso porcelanato antideslizante con coeficiente R11',
          categoria: 'Acabados',
          conforme_ia: true,
          evidencia_encontrada: 'Textura rugosa verificada visualmente en entrada y baños.',
          dictamen_ingeniero: 'Aprobado',
        },
      ],
      resumen_ia: 'Obra presenta 88% de conformidad general. Se recomienda aprobación condicionada al envío de la ficha RF-60 y ajuste de ubicación del rociador ACI.',
      riesgos_detectados: [
        'Interferencia física entre ducto HVAC y rociador ACI en eje 3-C.',
        'Documento de garantía de equipos de aire acondicionado pendiente de entrega.',
      ],
    },
    contratistas: MOCK_CONTRATISTAS[0],
    created_at: '2026-08-30T16:00:00Z',
    updated_at: '2026-08-30T16:20:00Z',
  },
];

export const MOCK_SOLICITUDES: SolicitudConRelaciones[] = [
  {
    id: 'sol-001',
    codigo: 'SOL-00001',
    titulo: 'Remodelación de Falso Techo e Iluminación Comercial',
    descripcion: 'Se requiere cambio total de luminarias fluorescentes a paneles LED inteligentes y reparación de placas de cielo raso dañadas.',
    local_id: 'loc-001',
    contratista_id: null,
    solicitante_id: 'usr-comercial-001',
    creado_por: 'auth-comercial-001',
    prioridad: 'Alta',
    fecha_limite: new Date(Date.now() + 3 * 86400000).toISOString(),
    presupuesto: 25000.0,
    estado_flujo: '1_NUEVO_REQUERIMIENTO',
    created_at: '2026-08-25T09:00:00Z',
    updated_at: '2026-08-25T09:00:00Z',
    locales: MOCK_LOCALES[0],
    contratistas: null,
  },
  {
    id: 'sol-002',
    codigo: 'SOL-00002',
    titulo: 'Adecuación de Isla Gastronómica - Tomas Eléctricas y Trampa de Grasa',
    descripcion: 'Habilitación de punto trifásico 380V de 15kW y trampa de grasa en acero inoxidable 304 para nueva freidora industrial.',
    local_id: 'loc-002',
    contratista_id: null,
    solicitante_id: 'usr-comercial-001',
    creado_por: 'auth-comercial-001',
    prioridad: 'Urgente',
    fecha_limite: new Date(Date.now() + 1 * 86400000).toISOString(),
    presupuesto: 18500.0,
    estado_flujo: '2_ESPERANDO_INFO_LOCAL',
    created_at: '2026-08-24T14:30:00Z',
    updated_at: '2026-08-26T10:00:00Z',
    locales: MOCK_LOCALES[1],
    contratistas: null,
  },
  {
    id: 'sol-003',
    codigo: 'SOL-00003',
    titulo: 'Ampliación de Sala de Ventas y Refuerzo de Muros Drywall',
    descripcion: 'Levantamiento técnico completado por tienda con planos arquitectónicos adjuntos y medidas en sitio.',
    local_id: 'loc-003',
    contratista_id: null,
    solicitante_id: 'usr-comercial-001',
    creado_por: 'auth-comercial-001',
    prioridad: 'Media',
    fecha_limite: new Date(Date.now() + 12 * 86400000).toISOString(),
    presupuesto: 35000.0,
    estado_flujo: '3_LEVANTAMIENTO_COMPLETO',
    created_at: '2026-08-22T11:00:00Z',
    updated_at: '2026-08-27T16:00:00Z',
    locales: MOCK_LOCALES[2],
    especificaciones_tecnicas: {
      id: 'esp-003',
      solicitud_id: 'sol-003',
      medidas_exactas_m2: 310.0,
      potencia_electrica_kw: 28.5,
      agua_contraincendio_psi: 75.0,
      tipo_local: 'Tienda Departamental / Retail',
      planos_url: 'https://storage.supabase.co/planos/plano_arquitectura_sol003.pdf',
      fotos_entorno_urls: [
        'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
      ],
      otros_requerimientos: { horario_trabajo: 'Nocturno (23:00 - 06:00)' },
      created_at: '2026-08-27T16:00:00Z',
      updated_at: '2026-08-27T16:00:00Z',
    },
    contratistas: null,
  },
  {
    id: 'sol-004',
    codigo: 'SOL-00004',
    titulo: 'Instalación de Sistema de Climatización VRF 10 HP',
    descripcion: 'Convocatoria abierta para proveedores HVAC. Se requiere equipo inverter ecológico R-410A y condensadora exterior.',
    local_id: 'loc-004',
    contratista_id: null,
    solicitante_id: 'usr-comercial-001',
    creado_por: 'auth-comercial-001',
    prioridad: 'Media',
    fecha_limite: new Date(Date.now() + 8 * 86400000).toISOString(),
    presupuesto: 62000.0,
    estado_flujo: '4_EN_LICITACION',
    created_at: '2026-08-20T10:00:00Z',
    updated_at: '2026-08-28T09:00:00Z',
    locales: MOCK_LOCALES[3],
    contratistas: null,
  },
  {
    id: 'sol-005',
    codigo: 'SOL-00005',
    titulo: 'Adecuación Integral y Cambio de Piso Comercial',
    descripcion: 'Propuesta recibida de Obras Express S.A.C. Evaluada por motor RAG con alerta de sobrecosto del +15.5%. Auditoría HITL requerida.',
    local_id: 'loc-001',
    contratista_id: 'cont-001',
    solicitante_id: 'usr-comercial-001',
    creado_por: 'auth-comercial-001',
    prioridad: 'Alta',
    fecha_limite: new Date(Date.now() + 5 * 86400000).toISOString(),
    presupuesto: 42000.0,
    estado_flujo: '5_EVALUANDO_COTIZACIONES',
    created_at: '2026-08-18T10:00:00Z',
    updated_at: '2026-08-28T10:10:00Z',
    locales: MOCK_LOCALES[0],
    contratistas: MOCK_CONTRATISTAS[0],
    cotizaciones: MOCK_COTIZACIONES,
  },
  {
    id: 'sol-006',
    codigo: 'SOL-00006',
    titulo: 'Instalación de Mampara de Vidrio Templado 10mm y Cortina de Aire',
    descripcion: 'Cotización adjudicada por Ingeniería. Sincronizada con ERP (Doc: OC-2026-8849). Contratista ejecutando obra en tienda.',
    local_id: 'loc-005',
    contratista_id: 'cont-001',
    solicitante_id: 'usr-comercial-001',
    creado_por: 'auth-comercial-001',
    prioridad: 'Baja',
    fecha_limite: new Date(Date.now() + 15 * 86400000).toISOString(),
    presupuesto: 14200.0,
    estado_flujo: '6_COTIZACION_APROBADA',
    created_at: '2026-08-15T09:00:00Z',
    updated_at: '2026-08-29T11:00:00Z',
    locales: MOCK_LOCALES[4],
    contratistas: MOCK_CONTRATISTAS[0],
    erp_sincronizacion: [
      {
        id: 'erp-001',
        solicitud_id: 'sol-006',
        erp_documento_id: 'OC-2026-8849',
        estado_pago: 'Aprobado_Para_Giro',
        monto_sincronizado: 14200.0,
        direccion: 'Salida',
        payload: { orden_compra: 'OC-2026-8849', proveedor_ruc: '20554896321' },
        created_at: '2026-08-29T11:00:00Z',
        updated_at: '2026-08-29T11:00:00Z',
      },
    ],
  },
  {
    id: 'sol-007',
    codigo: 'SOL-00007',
    titulo: 'Sistema de Extracción y Ventilación Mecánica para Cocina',
    descripcion: 'Contratista entregó informe final y 3 fotografías. IA Multimodal detectó interferencia leve en rociador ACI (Score: 88%).',
    local_id: 'loc-002',
    contratista_id: 'cont-001',
    solicitante_id: 'usr-comercial-001',
    creado_por: 'auth-comercial-001',
    prioridad: 'Alta',
    fecha_limite: new Date(Date.now() + 2 * 86400000).toISOString(),
    presupuesto: 31000.0,
    estado_flujo: '7_OBRA_VALIDADA',
    created_at: '2026-08-10T08:00:00Z',
    updated_at: '2026-08-30T16:30:00Z',
    locales: MOCK_LOCALES[1],
    contratistas: MOCK_CONTRATISTAS[0],
    informes_obra: MOCK_INFORMES_OBRA,
  },
  {
    id: 'sol-008',
    codigo: 'SOL-00008',
    titulo: 'Pintura Epóxica y Reparación de Pisos en Almacén',
    descripcion: 'Obra concluida y liquidada con acta de conformidad firmada por Supervisión de Operaciones.',
    local_id: 'loc-003',
    contratista_id: 'cont-001',
    solicitante_id: 'usr-comercial-001',
    creado_por: 'auth-comercial-001',
    prioridad: 'Baja',
    fecha_limite: new Date(Date.now() - 5 * 86400000).toISOString(),
    presupuesto: 11800.0,
    estado_flujo: 'CERRADO',
    created_at: '2026-08-01T08:00:00Z',
    updated_at: '2026-08-20T17:00:00Z',
    locales: MOCK_LOCALES[2],
    contratistas: MOCK_CONTRATISTAS[0],
  },
];

// Series para Dashboard Analítico BI
export const MOCK_BI_VOLUMEN_TIENDA: VolumenTiendaData[] = [
  { tienda: 'Plaza Norte', solicitudes: 18, activas: 6, cerradas: 12 },
  { tienda: 'Jockey Plaza', solicitudes: 14, activas: 5, cerradas: 9 },
  { tienda: 'Real Plaza Salaverry', solicitudes: 11, activas: 4, cerradas: 7 },
  { tienda: 'Mall del Sur', solicitudes: 9, activas: 3, cerradas: 6 },
  { tienda: 'Plaza San Miguel', solicitudes: 7, activas: 2, cerradas: 5 },
];

export const MOCK_BI_TIEMPO_ESTADO: TiempoEstadoData[] = [
  { estado: '1. Requerimiento', diasPromedio: 1.2, slaObjetivoDias: 2.0 },
  { estado: '2. Info Local', diasPromedio: 2.8, slaObjetivoDias: 3.0 },
  { estado: '3. Levantamiento', diasPromedio: 1.5, slaObjetivoDias: 2.0 },
  { estado: '4. Licitación', diasPromedio: 4.2, slaObjetivoDias: 5.0 },
  { estado: '5. Evaluación IA', diasPromedio: 1.1, slaObjetivoDias: 2.0 },
  { estado: '6. Aprobación ERP', diasPromedio: 0.8, slaObjetivoDias: 1.0 },
  { estado: '7. Validación Obra', diasPromedio: 1.9, slaObjetivoDias: 2.0 },
];

export const MOCK_BI_EFICIENCIA_CONTRATISTAS: EficienciaContratistaData[] = [
  { contratista: 'Climatización & Frío Total', diasPromedio: 3.2, scoreCalidad: 96.0, obrasCompletadas: 14 },
  { contratista: 'ElectroServicios Ing.', diasPromedio: 4.1, scoreCalidad: 92.5, obrasCompletadas: 11 },
  { contratista: 'Obras Express S.A.C.', diasPromedio: 5.4, scoreCalidad: 88.0, obrasCompletadas: 18 },
  { contratista: 'Diseño & Modular Retail', diasPromedio: 7.2, scoreCalidad: 81.0, obrasCompletadas: 6 },
];

export const MOCK_BI_DESVIACION_PRESUPUESTO: DesviacionPresupuestoData[] = [
  { name: 'Dentro del Presupuesto (≤ 5%)', value: 38, color: '#3F7A6E' },
  { name: 'Desviación Moderada (5% - 15%)', value: 12, color: '#E8A33D' },
  { name: 'Sobrecosto Crítico (> 15%)', value: 6, color: '#C4432A' },
];
